// Regenerates src/generated/catalog.ts from the AntSeedStats API catalogue (antseed-stats/src/lib/api/catalog.ts,
// a pure module with no server imports, so tsx can load it straight from the sister checkout).
//
//   npm run sync-catalog                       # ../antseed-stats
//   ANTSEEDSTATS_REPO=/path/to/antseed-stats npm run sync-catalog
//
// The output is committed: the published package must not depend on the sister repo being present.
import { execSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repo = resolve(process.env.ANTSEEDSTATS_REPO ?? join(here, "../../antseed-stats"));
const catalogPath = join(repo, "src/lib/api/catalog.ts");

type Catalog = typeof import("../../antseed-stats/src/lib/api/catalog.js");
const mod = (await import(pathToFileURL(catalogPath).href)) as Catalog;

let commit = "unknown";
try { commit = execSync("git rev-parse --short HEAD", { cwd: repo, encoding: "utf8" }).trim(); } catch { /* not a git checkout */ }

const entries = mod.API_CATALOG.map((e) => ({
  id: e.id,
  tool: mod.mcpToolName(e.id),
  group: e.group,
  method: e.method,
  path: e.path,
  summary: e.summary,
  desc: e.desc,
  params: e.params,
  example: e.example,
  page: e.page,
  prompt: e.prompt,
  cache: e.cache,
  sources: e.sources,
  schema: e.schema,
}));

const out = `// GENERATED by scripts/sync-catalog.ts from antseed-stats@${commit} (src/lib/api/catalog.ts) on ${new Date().toISOString()}.
// Do not edit: run \`npm run sync-catalog\` after the API catalogue changes, then \`npm run check-drift\`.
import type { CatalogEndpoint } from "../catalog.js";

export const SOURCE_COMMIT = ${JSON.stringify(commit)};
export const API_VERSION = ${JSON.stringify(mod.API_VERSION)};
export const API_BASE_PATH = ${JSON.stringify(mod.API_BASE_PATH)};
export const RATE_LIMIT_PER_MIN = ${mod.RATE_LIMIT_PER_MIN};
export const MCP_PUBLIC_URL = ${JSON.stringify(mod.MCP_PUBLIC_URL)};

export const CATALOG: CatalogEndpoint[] = ${JSON.stringify(entries, null, 2)};
`;

const target = join(here, "../src/generated/catalog.ts");
mkdirSync(dirname(target), { recursive: true });
writeFileSync(target, out);
console.log(`wrote ${target}: ${entries.length} endpoints from antseed-stats@${commit}`);
